DROP DATABASE IF EXISTS work_db;

CREATE DATABASE work_db;

USE work_db;

CREATE TABLE department (ID INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30));

CREATE TABLE role (ID INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(30), salary DECIMAL,  department_ID INT, FOREIGN KEY (department_ID) REFERENCES department(ID));

CREATE TABLE employee (ID INT PRIMARY KEY AUTO_INCREMENT,first_name VARCHAR(30), last_name VARCHAR(30), role_ID INT , manager_ID INT, FOREIGN KEY(role_ID) REFERENCES role(ID));
